"""Bilingual product copy for the native OSR Updater interface."""

from __future__ import annotations


TEXT: dict[str, dict[str, str]] = {
    "en": {
        "window_title": "OSR Updater — ESP32-S3",
        "product_name": "OSR Updater",
        "tagline": "ESP32-S3 firmware installation and controller recovery",
        "language": "中文",
        "connection": "Controller",
        "serial_port": "Serial device",
        "refresh": "Refresh",
        "inspect": "Inspect",
        "not_inspected": "Not inspected",
        "firmware": "Firmware file",
        "select_file": "Select file",
        "no_file": "No firmware file selected",
        "file_type": "Type",
        "file_size": "Size",
        "file_sha": "SHA-256",
        "application": "Application update",
        "recovery": "Full-flash image",
        "actions": "Installation",
        "normal_update": "Install firmware",
        "full_flash": "Full-flash installation",
        "restore_settings": "Factory Restore",
        "restore_from": "Factory vehicle-settings baseline",
        "no_settings_backups": "No verified vehicle-settings backups found",
        "select_full_flash_for_backups": "Select a full-flash firmware file to show compatible backups",
        "no_compatible_settings_backups": "No compatible vehicle-settings backup for the selected firmware",
        "recommended": "Recommended",
        "factory_baseline": "Factory baseline",
        "unknown_firmware": "Unidentified source firmware",
        "operation_snapshot": "Before full-flash installation",
        "restore_safety_snapshot": "Before settings restoration",
        "progress": "Progress",
        "activity": "Activity",
        "backup_path": "Vehicle-settings backup",
        "complete_settings_backup": "Complete settings backup",
        "complete_settings_metadata": "Backup metadata",
        "audit_path": "Audit log",
        "open_backups": "Open backups",
        "open_audit": "Open",
        "backup_available": "A vehicle-settings backup is available. Use Open backups to view it.",
        "audit_available": "An audit record is available. Use Open to view it.",
        "backup_directory_opened": "Backup folder opened",
        "audit_directory_opened": "Audit folder opened",
        "ready": "Ready",
        "working": "Operation in progress",
        "success": "Operation completed successfully",
        "completed_unverified": "Write completed; controller startup requires verification",
        "failed": "Operation requires attention",
        "about": "Version {version} · winter@osrbot.com",
        "select_dialog": "Select an ESP32-S3 firmware file",
        "firmware_file_filter": "Firmware image",
        "all_files_filter": "All files",
        "select_settings_backup": "Select vehicle-settings backup metadata",
        "settings_backup_filter": "Vehicle-settings backup metadata",
        "confirm_install_title": "Confirm firmware installation",
        "confirm_install": "The selected application will be installed through App OTA. The NVS partition is not erased or rewritten. Continue?",
        "confirm_prepare_title": "Confirm full-flash installation",
        "confirm_prepare": "Keep USB connected and enter ESP32-S3 recovery mode with BOOT/RESET. The updater will detect the re-enumerated ROM port, store the complete current settings, and then request final confirmation before any erase. Continue?",
        "confirm_erase_title": "Final destructive confirmation",
        "confirm_erase": "Keep USB connected and remain in recovery mode. The complete flash will be erased and replaced. Saved settings are restored automatically only when the source and target layouts match; otherwise the backup is retained without writing it into an unknown layout. Use Open backups if you want to inspect the stored files. Continue?",
        "confirm_controller_restore_title": "Confirm factory restore",
        "confirm_controller_restore": "The selected full-flash firmware and the fixed factory vehicle-settings baseline will be used together. Keep USB connected and enter ESP32-S3 recovery mode with BOOT/RESET. The updater will verify the controller, firmware layout, and backup before erasing anything. Continue?",
        "confirm_erase_restore": "Final confirmation: erase the complete flash, install the selected full-flash firmware, and restore the selected saved vehicle settings. The current settings have also been saved as a safety backup. Continue?",
        "confirm_restore_title": "Confirm vehicle-settings restoration",
        "confirm_restore": "Select a verified backup metadata file, keep USB connected, and enter ESP32-S3 recovery mode with BOOT/RESET. The updater will verify the controller identity and settings layout, save the current settings, restore the selected settings, and read them back before reset. Continue?",
        "confirmation_cancelled": "Confirmation was cancelled; no destructive operation started.",
        "error_open_directory": "The selected folder could not be opened.",
        "inspect_ok": "Controller inspection completed",
        "event_select": "Firmware file validated",
        "event_inspect_started": "Inspecting the connected controller",
        "event_inspect_completed": "Controller inspection completed",
        "event_validate_started": "Validating the selected firmware file",
        "event_validate_completed": "Firmware file validation completed",
        "event_backup_started": "Backing up vehicle settings",
        "event_backup_completed": "Vehicle-settings backup stored and verified",
        "event_backup_unavailable": "A readable vehicle-settings backup is unavailable",
        "event_flash_app_started": "Installing the application; stored vehicle settings are not erased",
        "event_flash_app_progress": "Installing application",
        "event_rom_waiting": "Waiting for ESP32-S3 recovery mode",
        "event_rom_started": "Connecting to ESP32-S3 recovery mode",
        "event_rom_completed": "Recovery controller and settings backup verified",
        "event_raw_settings_started": "Reading the complete vehicle-settings partition",
        "event_raw_settings_completed": "Complete current settings snapshot stored and verified",
        "event_raw_settings_unavailable": "The current NVS layout could not be identified; full-flash installation was not started",
        "event_confirm_erase_ready": "Complete settings backup verified; final confirmation is ready",
        "event_erase_started": "Erasing the complete flash",
        "event_erase_completed": "Complete flash erase finished",
        "event_recovery_flash_started": "Installing the selected full-flash image",
        "event_recovery_flash_progress": "Installing the selected full-flash image",
        "event_recovery_flash_completed": "Selected full-flash image installed",
        "event_settings_restore_started": "Restoring vehicle settings",
        "event_settings_restore_progress": "Restoring vehicle settings",
        "event_settings_restore_completed": "Vehicle settings restored and verified",
        "event_restore_backup_started": "Saving the current vehicle settings before restoration",
        "event_restore_backup_completed": "Current vehicle settings stored and verified",
        "event_reconnect_started": "Waiting for the restored controller",
        "event_manual_reset_required": "Press RESET once to restart the controller",
        "event_result_success": "Operation completed successfully",
        "event_result_completed_unverified": "Write completed; controller startup requires verification",
        "event_result_failed": "Operation requires attention",
        "result_app_success": "Application update completed and the available checks passed. The NVS partition was preserved.",
        "result_app_unverified": "Application transfer completed, but startup or optional settings checks were not verified. Do not repeat the App write automatically.",
        "result_full_success": "Full-flash installation completed. The complete settings backup was retained because the target layout differs. Press RESET, then inspect the controller again.",
        "result_full_unverified": "Full-flash write completed, but controller startup could not be verified. The complete settings backup was retained.",
        "result_full_restored": "Full-flash installation completed. The saved vehicle settings were restored, read back, and verified. Press RESET, then inspect the controller again.",
        "result_full_restored_unverified": "Full-flash write and vehicle-settings readback completed, but controller startup could not be verified.",
        "result_settings_restored": "The selected vehicle settings were restored and verified. The previous settings were retained as a safety backup. Inspect the controller after restart.",
        "device_version": "Firmware",
        "device_protocol": "Interface",
        "device_voltage": "Battery",
        "device_state": "State",
        "device_ready": "Ready",
        "device_attention": "Attention required",
        "device_reinspect": "Restarted; inspect again",
        "device_inspecting": "Inspecting",
        "device_unavailable": "Recovery mode or unsupported firmware",
        "inspect_unavailable_detail": "Firmware information is unavailable. The selected port was retained; the controller may be in ESP32-S3 ROM download mode or the running firmware may not implement the OSR interface.",
        "unknown": "Unknown",
        "error_no_file": "Select a firmware file first.",
        "error_application_only": "The selected file is not an application image.",
        "error_recovery_only": "The selected file is not a full-flash image.",
        "error_restore_requires_full_image": "Select the full-flash firmware image to restore first.",
        "error_restore_requires_backup": "No verified vehicle-settings backup is selected.",
        "error_busy": "Wait for the current operation to finish.",
        "error_serial_in_use": "The selected serial port is in use by ROS or another program. Stop the program using the controller, then try again.",
        "error_tk": "The native interface requires Python Tk support.",
        "guidance_recovery_required": "Next step: keep the verified backup and use full-flash installation. Do not repeat an App update.",
        "guidance_full_flash_required": "Next step: this running firmware does not support OSR App OTA. Select a full-flash image, enter recovery mode with BOOT/RESET, and use full-flash installation.",
        "guidance_do_not_retry": "Next step: do not install the application again. Keep the backup and contact OSRBOT support.",
        "guidance_retry_allowed": "Next step: correct the reported condition, then retry the same installation.",
        "guidance_contact_support": "Next step: keep the backup and audit log, then contact OSRBOT support before retrying.",
        "manual_reset_title": "Start the installed firmware",
        "manual_reset_required": "Full-flash writing is complete. Press RESET once to restart the controller. The serial-device list will refresh automatically; then select Inspect.",
    },
    "zh": {
        "window_title": "OSR Updater — ESP32-S3",
        "product_name": "OSR Updater",
        "tagline": "ESP32-S3 固件安装与控制器恢复",
        "language": "English",
        "connection": "控制器",
        "serial_port": "串口设备",
        "refresh": "刷新",
        "inspect": "检查设备",
        "not_inspected": "尚未检查",
        "firmware": "固件文件",
        "select_file": "选择文件",
        "no_file": "尚未选择固件文件",
        "file_type": "类型",
        "file_size": "大小",
        "file_sha": "SHA-256",
        "application": "应用程序更新",
        "recovery": "完整烧写镜像",
        "actions": "安装操作",
        "normal_update": "安装固件",
        "full_flash": "完整烧写",
        "restore_settings": "恢复出厂",
        "restore_from": "出厂车辆设置基准",
        "no_settings_backups": "没有找到已验证的车辆设置备份",
        "select_full_flash_for_backups": "选择完整烧写固件后显示匹配的车辆设置备份",
        "no_compatible_settings_backups": "没有与当前固件匹配的车辆设置备份",
        "recommended": "推荐",
        "factory_baseline": "出厂备份",
        "unknown_firmware": "来源固件无法识别",
        "operation_snapshot": "完整烧写前备份",
        "restore_safety_snapshot": "恢复设置前安全备份",
        "progress": "进度",
        "activity": "执行记录",
        "backup_path": "车辆设置备份",
        "complete_settings_backup": "完整设置备份",
        "complete_settings_metadata": "备份元数据",
        "audit_path": "审计日志",
        "open_backups": "打开备份",
        "open_audit": "打开",
        "backup_available": "车辆设置备份已保存，请点击“打开备份”查看。",
        "audit_available": "审计记录已保存，请点击“打开”查看。",
        "backup_directory_opened": "备份文件夹已打开",
        "audit_directory_opened": "审计文件夹已打开",
        "ready": "就绪",
        "working": "正在执行操作",
        "success": "操作成功完成",
        "completed_unverified": "写入已完成，需确认控制器启动状态",
        "failed": "操作需要处理",
        "about": "版本 {version} · winter@osrbot.com",
        "select_dialog": "选择 ESP32-S3 固件文件",
        "firmware_file_filter": "固件镜像",
        "all_files_filter": "所有文件",
        "select_settings_backup": "选择车辆设置备份元数据",
        "settings_backup_filter": "车辆设置备份元数据",
        "confirm_install_title": "确认安装固件",
        "confirm_install": "将通过 App OTA 安装所选应用程序。此过程不会擦除或改写 NVS 分区。是否继续？",
        "confirm_prepare_title": "确认完整烧写",
        "confirm_prepare": "请保持 USB 连接并通过 BOOT/RESET 进入 ESP32-S3 恢复模式。客户端将自动发现重新枚举的 ROM 端口并保存当前完整设置；任何擦除开始前还会再次请求最终确认。是否继续？",
        "confirm_erase_title": "最终破坏性操作确认",
        "confirm_erase": "请保持 USB 连接和恢复模式。完整 Flash 将被擦除并替换。仅当源端和目标布局一致时，工具才自动恢复已保存的设置；布局不一致时只保留备份，不向未知布局写入。如需核对文件，请点击“打开备份”。是否继续？",
        "confirm_controller_restore_title": "确认恢复出厂",
        "confirm_controller_restore": "将组合使用当前选择的完整烧写固件和固定的出厂车辆设置基准。请保持 USB 连接并通过 BOOT/RESET 进入 ESP32-S3 恢复模式。擦除前，客户端会校验控制器、固件布局和备份。是否继续？",
        "confirm_erase_restore": "最终确认：擦除完整 Flash，安装所选完整烧写固件，并恢复所选车辆设置。当前设置也已另存为安全备份。是否继续？",
        "confirm_restore_title": "确认恢复车辆设置",
        "confirm_restore": "请选择已验证的备份元数据文件，保持 USB 连接，并通过 BOOT/RESET 进入 ESP32-S3 恢复模式。客户端会核对控制器身份和设置分区布局，先保存当前设置，再写入所选设置并逐字节回读验证。是否继续？",
        "confirmation_cancelled": "已取消确认，未启动破坏性操作。",
        "error_open_directory": "无法打开所选文件夹。",
        "inspect_ok": "控制器检查完成",
        "event_select": "固件文件验证通过",
        "event_inspect_started": "正在检查已连接的控制器",
        "event_inspect_completed": "控制器检查完成",
        "event_validate_started": "正在验证所选固件文件",
        "event_validate_completed": "固件文件验证完成",
        "event_backup_started": "正在备份车辆设置",
        "event_backup_completed": "车辆设置备份已保存并验证",
        "event_backup_unavailable": "无法读取车辆设置备份",
        "event_flash_app_started": "正在安装应用程序；已保存的车辆设置不会被擦除",
        "event_flash_app_progress": "正在安装应用程序",
        "event_rom_waiting": "正在等待 ESP32-S3 恢复模式",
        "event_rom_started": "正在连接 ESP32-S3 恢复模式",
        "event_rom_completed": "恢复模式控制器和设置备份已验证",
        "event_raw_settings_started": "正在读取完整车辆设置分区",
        "event_raw_settings_completed": "当前完整设置快照已保存并验证",
        "event_raw_settings_unavailable": "无法识别当前 NVS 布局，未开始完整烧写",
        "event_confirm_erase_ready": "完整设置备份已验证，可以进行最终确认",
        "event_erase_started": "正在擦除完整 Flash",
        "event_erase_completed": "完整 Flash 擦除完成",
        "event_recovery_flash_started": "正在安装所选完整烧写镜像",
        "event_recovery_flash_progress": "正在安装所选完整烧写镜像",
        "event_recovery_flash_completed": "所选完整烧写镜像已安装",
        "event_settings_restore_started": "正在恢复车辆设置",
        "event_settings_restore_progress": "正在恢复车辆设置",
        "event_settings_restore_completed": "车辆设置已恢复并验证",
        "event_restore_backup_started": "恢复前正在保存当前车辆设置",
        "event_restore_backup_completed": "当前车辆设置已保存并验证",
        "event_reconnect_started": "正在等待控制器重新连接",
        "event_manual_reset_required": "请按一次 RESET 重启控制器",
        "event_result_success": "操作成功完成",
        "event_result_completed_unverified": "写入已完成，需确认控制器启动状态",
        "event_result_failed": "操作需要处理",
        "result_app_success": "应用程序更新完成，可用检查均通过；NVS 分区已保留。",
        "result_app_unverified": "应用程序传输已完成，但启动状态或可选设置检查未能确认。不要自动重复 App 写入。",
        "result_full_success": "完整烧写完成。因目标布局不同，完整设置备份已保留但未写回。请按一次 RESET，然后重新检查设备。",
        "result_full_unverified": "完整镜像写入完成，但控制器启动状态未能确认；完整设置备份已保留。",
        "result_full_restored": "完整烧写完成，已保存的车辆设置已恢复并逐字节回读验证。请按一次 RESET，然后重新检查设备。",
        "result_full_restored_unverified": "完整镜像和车辆设置均已写入且回读验证，但控制器启动状态未能确认。",
        "result_settings_restored": "所选车辆设置已恢复并验证；恢复前的设置已作为安全备份保留。控制器重启后请重新检查设备。",
        "device_version": "固件版本",
        "device_protocol": "接口协议",
        "device_voltage": "电池电压",
        "device_state": "设备状态",
        "device_ready": "就绪",
        "device_attention": "需要处理",
        "device_reinspect": "已重启，请重新检查",
        "device_inspecting": "正在检查",
        "device_unavailable": "恢复模式或固件不支持检查",
        "inspect_unavailable_detail": "无法读取固件信息。当前选择的串口已保留；控制器可能处于 ESP32-S3 ROM 下载模式，或当前固件没有实现 OSR 接口。",
        "unknown": "未知",
        "error_no_file": "请先选择固件文件。",
        "error_application_only": "所选文件不是应用程序镜像。",
        "error_recovery_only": "所选文件不是完整烧写镜像。",
        "error_restore_requires_full_image": "请先选择用于恢复的完整烧写固件。",
        "error_restore_requires_backup": "尚未选择已验证的车辆设置备份。",
        "error_busy": "请等待当前操作完成。",
        "error_serial_in_use": "所选串口正被 ROS 或其他程序占用。请先停止占用控制器串口的程序，然后重试。",
        "error_tk": "原生界面需要 Python Tk 支持。",
        "guidance_recovery_required": "下一步：保留已验证的备份并使用完整烧写，不要重复执行 App 更新。",
        "guidance_full_flash_required": "下一步：当前运行固件不支持 OSR App OTA。请选择完整烧写镜像，通过 BOOT/RESET 进入恢复模式，然后执行完整烧写。",
        "guidance_do_not_retry": "下一步：不要再次安装应用程序，请保留备份并联系 OSRBOT 支持。",
        "guidance_retry_allowed": "下一步：排除提示的问题后，重新执行同一次安装。",
        "guidance_contact_support": "下一步：保留备份和审计日志，重试前请联系 OSRBOT 支持。",
        "manual_reset_title": "启动已安装固件",
        "manual_reset_required": "完整镜像写入已经完成。请按一次 RESET 重启控制器。串口列表将自动刷新，随后点击“检查设备”。",
    },
}


def text(language: str, key: str, **values: object) -> str:
    table = TEXT.get(language, TEXT["en"])
    template = table.get(key, TEXT["en"].get(key, key))
    return template.format(**values)


def event_text(language: str, phase: str, status: str, fallback: str) -> str:
    key = f"event_{phase}_{status}"
    translated = text(language, key)
    return fallback if translated == key else translated
